# Generated by Django 2.1.5 on 2019-02-11 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usernotesmap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'usernotesmap',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('notesid', models.ForeignKey(db_column='notesid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='articles.User')),
                ('notestitle', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'notes',
                'managed': False,
            },
        ),
    ]
